version: '3.8'

services:
  server:
    image: "rusty-server"
    build:
      context: ./server
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    ports:
      - "1234:1234"
    env_file:
      - .env

  client:
    image: "rusty-client"
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 0  # Start with no clients
    env_file:
      - .env
    ports:
      - "4321:4321"
