version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ServerDockerfile  # Ensure this is the correct path to your server Dockerfile
    ports:
      - "1234:1234"
    environment:
      - SERVER_PORT=1234
      - AUTH_KEY=${AUTH_KEY}
    env_file:
      - .env

  client:
    build:
      context: .
      dockerfile: ClientDockerfile  # Ensure this is the correct path to your client Dockerfile
    deploy:
      replicas: 5
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - AUTH_KEY=${AUTH_KEY}
    env_file:
      - .env
    depends_on:
      - server

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "2345:80"
