version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    ports:
      - "1234:1234"
    env_file:
      - .env  # Adjust this path

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    tty: true   # Ensures TTY support for terminal interaction
    env_file:
      - .env  # Adjust this path
    depends_on:
      - server

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "2345:80"


