version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    env_file:
      - ../.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    deploy:
      replicas: 5
    env_file:
      - ../.env
    depends_on:
      - server

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "2345:80"

